version: '3'

services:
  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: node
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 30s docker-entrypoint.sh
    command: bash -c "mysql -hmysql -uroot -pabc987 -A < /usr/src/app/setup.sql && node /usr/src/app/index.js"
    tty: true
    depends_on:
      - mysql
    volumes:
      - ./node:/usr/src/app
    networks:
      - node-network
    restart: unless-stopped
  
  nginx:
    image: nginx:1.23.0-alpine
    container_name: nginx
    tty: true
    depends_on:
      - node
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - node-network
    ports:
      - "8080:80"
    restart: unless-stopped

  mysql:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=abc987
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - node-network
    restart: unless-stopped

networks:
  node-network:
    driver: bridge